### PR TITLE
Update Fabric.podspec

### PR DESCRIPTION
**Pull request by bonebox**
Copy Crashlytics header files so they don't have to be manually copied into the project.

### CODE REVIEW

**Comment by zergtmn** [comment]
Could you please provide a bit more explanation why this is needed? Why do you have to copy the header files into the project?

**Comment by bonebox** [comment]
If someone needs to import the header file into a class in their project in order to call its methods, this is necessary.  With the current podspec, a project cannot locate the header file.

**Comment by zergtmn** [comment]
Sorry, I cannot reproduce the issue. Simply importing framework headers as usual works with the current podspec:
```
#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>
```

**Comment by bonebox** [comment]
That does work when using it directly in an app project, but the problem presents itself when attempting to create a new podspec for a library that uses this one as a dependency.  The podspec lint will fail with the following:
```fatal error: 'Crashlytics/Crashlytics.h' file not found
#import <Crashlytics/Crashlytics.h>

I copied your podspec into a private CocoaPods repo with my proposed changes, and it works just fine.

**Comment by zergtmn** [comment]
Ok, I see. Perhaps it'd be enough to add only xcconfig if you import Crashlytics/Crashlytics.h instead of just Crashlytics.h
```diff
@@ -9,6 +9,7 @@ Pod::Spec.new do |spec|
   spec.source       = { :git => "https://github.com/zergtmn/Fabric.git", :tag => "v#{spec.version}" }
   spec.requires_arc = true
   spec.default_subspec = "Core"
+  spec.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/Fabric"' }
 
   spec.subspec "Core" do |core|
     core.vendored_frameworks = "Fabric.framework"
```
Could you test with this patch to see if it works?

**Comment by bonebox** [comment]
That worked, thanks.

**Pull request closed without merging**
