### PR TITLE
Fabric v1.2.5 & Crashlytics v3.0.8 update

### PR DESCRIPTION
**Pull request by mattak**
I would like to update Fabric & Crashlytics latest version...
Is there any reason not update sdk verison?

### CODE REVIEW

**Comment by sodastsai** [comment]
:+1:

**Comment by asidden** [comment]
please, merge this in :+1:

**Comment by Panajev** [comment]
Please review and merge :+1:

**Comment by k06a** [comment]
@zergtmn what are you waiting for?

**Comment by k06a** [comment]
:+1: for merge

**Comment by rsvienty-solstice** [comment]
:+1: love to have this ASAP.

**Comment by RaneClowd** [comment]
:+1: me too

**Comment by Alexs1987** [comment]
:+1: Awesome, please merge it :)

**Comment by zakavila** [comment]
:+1: :+1: :+1:

**Comment by zergtmn** [comment]
I've pushed v1.3.0 where I've updated all frameworks at once. Anyway thanks for your efforts!

**Comment by mattak** [comment]
thanks!

**Pull request closed without merging**
